
POST http://localhost:3000/api/request-news
Content-Type: application/json

{
	"query": "Tesla",
	"sortBy": "relevancy",
	"dateRange": {
		"startDate": "2023-07-10",
		"endDate": "2023-07-30"
	},
    "page": 10

}
