version: "3.9"
services:
    hekaBackend:
        env_file:
            - ./backend/.env.prod
        image: "uflock/heka-backend"
        build:
            context: ./backend
            dockerfile: Dockerfile
            target: production
        ports:
            - "3000:3000"
        networks:
            - frontend
            - backend
    hekaFrontend:
        image: "uflock/heka-frontend"
        build:
            context: ./frontend
            dockerfile: Dockerfile
            target: production
        ports:
            - "80:80"
        networks:
            - frontend
networks:
    frontend:
    backend:
