# This is a basic workflow to help you get started with Actions

name: BACKEND-CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'backend/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "test-and-build"
   test-and-build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Install dependencies
      - name: "Install dependencies"
        run: cd backend && npm install

      # Run tests
      - name: "Run tests"
        run: cd backend && npm run test:ci

      # Test if builds successfully
      - name: "Test build"
        run: cd backend && npm run build
